<?php

namespace CoeurBundle\Repository;

/**
 * CraftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CraftRepository extends \Doctrine\ORM\EntityRepository
{
}
