<?php

namespace CoeurBundle\Repository;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllItems()
    {
        $qb = $this->createQueryBuilder('i');

        $qb
            ->join('i.craft', 'c')
            ->addSelect('c')
        ;

        $qb->andWhere('c.items = i.id');

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
